<?php

/* Copyright [2011, 2012, 2013] da Universidade Federal de Juiz de Fora
 * Este arquivo é parte do programa Framework Maestro.
 * O Framework Maestro é um software livre; você pode redistribuí-lo e/ou 
 * modificá-lo dentro dos termos da Licença Pública Geral GNU como publicada 
 * pela Fundação do Software Livre (FSF); na versão 2 da Licença.
 * Este programa é distribuído na esperança que possa ser  útil, 
 * mas SEM NENHUMA GARANTIA; sem uma garantia implícita de ADEQUAÇÃO a qualquer
 * MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a Licença Pública Geral GNU/GPL 
 * em português para maiores detalhes.
 * Você deve ter recebido uma cópia da Licença Pública Geral GNU, sob o título
 * "LICENCA.txt", junto com este programa, se não, acesse o Portal do Software
 * Público Brasileiro no endereço www.softwarepublico.gov.br ou escreva para a 
 * Fundação do Software Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301, USA.
 */

return array(
    /* interfaces */
    'iaccess' => "interfaces/iaccess.php",
    'igroup' => "interfaces/igroup.php",
    'ilog' => "interfaces/ilog.php",
    'isession' => "interfaces/isession.php",
    'itransaction' => "interfaces/itransaction.php",
    'iuser' => "interfaces/iuser.php",
    'idatabase' => "interfaces/idatabase.php",
    'ipersistentmanager' => "interfaces/ipersistentmanager.php",
    /* database */
    'mdatabase' => "database/mdatabase.php",
    'msql' => "database/msql.php",
    'mquery' => "database/mquery.php",
    'msqllogger' => "database/msqllogger.php",
    /* exceptions */
    'iexception' => "services/mexception.php",
    'mexception' => "services/mexception.php",
    'emexception' => "services/mexception.php",
    'einoutexception' => "services/mexception.php",
    'ebusinessexception' => "services/mexception.php",
    'emodelexception' => "services/mexception.php",
    'edbexception' => "database/mdbexception.php",
    'econtrolexception' => "services/mexception.php",
    'eusesexception' => "services/mexception.php",
    'esessionexception' => "services/mexception.php",
    'enotfoundexception' => "services/mexception.php",
    'eruntimeexception' => "services/mexception.php",
    'etimeoutexception' => "services/mexception.php",
    'efilenotfoundexception' => "services/mexception.php",
    'esecurityexception' => "services/mexception.php",
    'econtrollerexception' => "services/mexception.php",
    'eloginexception' => "services/mexception.php",
    /* mvc */
    'mmodel' => "mvc/mmodel.php",
    'mbusinessmodel' => "mvc/mbusinessmodel.php",
    'mbusiness' => "mvc/mbusiness.php",
    'mhandler' => "mvc/mhandler.php",
    'mfrontcontroller' => "mvc/mfrontcontroller.php",
    'mcontroller' => "mvc/mcontroller.php",
    'mfilter' => "mvc/mfilter.php",
    'mservice' => "mvc/mservice.php",
    'mflowcontroller' => "mvc/mflowcontroller.php",
    'mview' => "mvc/mview.php",
    'mflowview' => "mvc/mflowview.php",
    'mrouter' => "mvc/mrouter.php",
    'mresult' => "mvc/results/mresult.php",
    'mrenderpage' => "mvc/results/mrenderpage.php",
    'mrenderjson' => "mvc/results/mrenderjson.php",
    'mrendertemplate' => "mvc/results/mrendertemplate.php",
    'mrenderprompt' => "mvc/results/mrenderprompt.php",
    'mrenderbinary' => "mvc/results/mrenderbinary.php",
    'mnotfound' => "mvc/results/mnotfound.php",
    'minternalerror' => "mvc/results/minternalerror.php",
    'mruntimeerror' => "mvc/results/mruntimeerror.php",
    'mredirect' => "mvc/results/mredirect.php",
    'mbrowserwindow' => "mvc/results/mbrowserwindow.php",
    'mbrowserfile' => "mvc/results/mbrowserfile.php",
    /* persistence */
    'basecriteria' => "persistence/criteria/basecriteria.php",
    'persistentcondition' => "persistence/criteria/persistentcondition.php",
    'criteriaattribute' => "persistence/criteria/criteriaattribute.php",
    'conditioncriteria' => "persistence/criteria/conditioncriteria.php",
    'dmlcriteria' => "persistence/criteria/dmlcriteria.php",
    'updatecriteria' => "persistence/criteria/updatecriteria.php",
    'deletecriteria' => "persistence/criteria/deletecriteria.php",
    'havingcriteria' => "persistence/criteria/havingcriteria.php",
    //'orderentry' => "persistence/criteria/orderentry.php",
    'associationcriteria' => "persistence/criteria/associationcriteria.php",
    'persistentcriteria' => "persistence/criteria/persistentcriteria.php",
    'persistentoperand' => "persistence/criteria/persistentoperand.php",
    'operandnull' => "persistence/criteria/persistentoperand.php",
    'operandvalue' => "persistence/criteria/persistentoperand.php",
    'operandattributemap' => "persistence/criteria/persistentoperand.php",
    'operandarray' => "persistence/criteria/persistentoperand.php",
    'operandcriteria' => "persistence/criteria/persistentoperand.php",
    'operandobject' => "persistence/criteria/persistentoperand.php",
    'operandfunction' => "persistence/criteria/persistentoperand.php",
    'operandexpression' => "persistence/criteria/persistentoperand.php",
    'operandstring' => "persistence/criteria/persistentoperand.php",
    'retrievecriteria' => "persistence/criteria/retrievecriteria.php",
    'selectioncriteria' => "persistence/criteria/selectioncriteria.php",
    'cursor' => "persistence/cursor.php",
    'association' => "persistence/association.php",
    'attributemap' => "persistence/map/attributemap.php",
    'classmap' => "persistence/map/classmap.php",
    'associationmap' => "persistence/map/associationmap.php",
    'persistentmanager' => "persistence/persistentmanager.php",
    'persistentsession' => "persistence/persistentsession.php",
    'persistentmanagerfactory' => "persistence/persistentmanagerfactory.php",
    'persistentobject' => "persistence/persistentobject.php",
    'phpconfigloader' => "persistence/phpconfigloader.php",
    'xmlconfigloader' => "persistence/xmlconfigloader.php",
    /* security */
    'mauth' => "security/mauth.php",
    'mauthdb' => "security/mauthdb.php",
    'mauthdbmd5' => "security/mauthdbmd5.php",
    'mauthldapmd5' => "security/mauthldapmd5.php",
    'mlogin' => "security/mlogin.php",
    'mperms' => "security/mperms.php",
    'mssl' => "security/mssl.php",
    /* testing */
    'testing\fakepersistentmanager' => "testing/fakepersistentmanager.php",
    'testing\methodinvoker' => "testing/methodinvoker.php",
    'testing\inmemorydatabase' => "testing/inmemorydatabase.php",
    /* utils */
    'mnull' => "utils/mnull.php",
    'mrc4crypt' => "utils/mrc4crypt.php",
    'mmd5crypt' => "utils/mmd5crypt.php",
    'mcsvdump' => "utils/mcsvdump.php",
    'mcsv2array' => "utils/mcsv2array.php",
    'mlist' => "utils/mlist.php",
    'mstringlist' => "utils/mlist.php",
    'mstringmap' => "utils/mlist.php",
    'mobjectlist' => "utils/mlist.php",
    'mphonetic' => "utils/mphonetic.php",
    'msimplexml' => "utils/msimplexml.php",
    'mtree' => "utils/mtree.php",
    'mutil' => "utils/mutil.php",
    'mvardump' => "utils/mutil.php",
    'minvertdate' => "utils/mivertdate.php",
    'mkrono' => "utils/mkrono.php",
    //'mformatvalue' => "utils/mutil.php",
    'mcurrencyformatter' => "utils/mcurrencyformatter.php",
    'mquotedprintable' => "utils/mquotedprintable.php",
    //'mtreearray' => "utils/mutil.php",
    'mdummy' => "utils/mutil.php",
    'mdataobject' => "utils/mutil.php",
    'mxmltreeelement' => "utils/mxmltree.php",
    'mxmlnode' => "utils/mxmltree.php",
    'mxmltree' => "utils/mxmltree.php",
    'mwiki' => "utils/mwiki.php",
    /* services */
    'mcontext' => "services/mcontext.php",
    'mdump' => "services/mdump.php",
    'mhistory' => "services/mhistory.php",
    'mmailer' => "services/mmailer.php",
    'mlog' => "services/mlog.php",
    'mprofile' => "services/mprofile.php",
    'msession' => "services/msession.php",
    'mtrace' => "services/mtrace.php",
    'mconfigloader' => "services/mconfigloader.php",
    'mautoload' => "services/mautoload.php",
    'mcache' => "services/cache/mcache.php",
    'mjson' => "services/mjson.php",
    'mmessages' => 'services/mmessages.php',
    'mldap' => "services/mldap.php",
    'mcertificate' => "services/mcertificate.php",
    /* http */
    'mresponse' => "services/http/mresponse.php",
    'mrequest' => "services/http/mrequest.php",
    'mcookie' => "services/http/mhttp.php",
    'mheader' => "services/http/mhttp.php",
    'mstatuscode' => "services/http/mhttp.php",
    /* types */
    'mtypes' => "types/mtypes.php",
    'mtype' => "types/mtype.php",
    'mdate' => "types/mdate.php",
    'mtimestamp' => "types/mtimestamp.php",
    'mcurrency' => "types/mcurrency.php",
    'mrange' => "types/mrange.php",
    'mfile' => "types/mfile.php",
    'mcpf' => "types/mcpf.php",
    'mnit' => "types/mnit.php",
    'mcnpj' => "types/mcnpj.php",
    'menumbase' => "types/menumbase.php",
    'menumdatabase' => "types/menumdatabase.php",
    /* data types */
    'msexo' => "types/data/msexo.php",
    'mestadocivil' => "types/data/mestadocivil.php",
    'mboolean' => "types/data/mboolean.php",
    'mstatusassinatura' => "types/data/mstatusassinatura.php",
    /* data validators */
    'mdatavalidator' => 'utils/mdatavalidator.php',
    'doctrine_validator_driver' => 'utils/datavalidator/driver.php',
    'doctrine_validator_notnull' => 'utils/datavalidator/notnull.php',
    'doctrine_validator_notblank' => 'utils/datavalidator/notblank.php',
    'doctrine_validator_date' => 'utils/datavalidator/date.php',
    'doctrine_validator_minlength' => 'utils/datavalidator/minlength.php',
    'doctrine_validator_maxlength' => 'utils/datavalidator/maxlength.php',
    'doctrine_validator_range' => 'utils/datavalidator/range.php',
    'doctrine_validator_past' => 'utils/datavalidator/past.php',
    /* extensions */
    'json' => "extensions/json.php",
    'phpmailer' => "extensions/phpmailer/class.phpmailer.php",
    'smtp' => "extensions/phpmailer/class.smtp.php",
    'cezpdf' => "extensions/ezpdf/class.ezpdf.php",
    'cpdf' => "extensions/ezpdf/class.pdf.php",
    'phpexcel' => "extensions/PHPExcel.php",
	'tcpdf' => "extensions/tcpdf/tcpdf.php",
    'phplot' => "extensions/phplot/phplot.php",
);
